package store

func (s *Submission) ToUpdateParam() UpdateSubmissionParams {

	return UpdateSubmissionParams{
		ID:                                   s.ID,
		SourceCode:                           s.SourceCode,
		LanguageID:                           s.LanguageID,
		Stdin:                                s.Stdin,
		ExpectedOutput:                       s.ExpectedOutput,
		Stdout:                               s.Stdout,
		StatusID:                             s.StatusID,
		CreatedAt:                            s.CreatedAt,
		FinishedAt:                           s.FinishedAt,
		Time:                                 s.Time,
		Memory:                               s.Memory,
		Stderr:                               s.Stderr,
		Token:                                s.Token,
		NumberOfRuns:                         s.NumberOfRuns,
		CpuTimeLimit:                         s.CpuTimeLimit,
		CpuExtraTime:                         s.CpuExtraTime,
		WallTimeLimit:                        s.WallTimeLimit,
		MemoryLimit:                          s.MemoryLimit,
		StackLimit:                           s.StackLimit,
		MaxProcessesAndOrThreads:             s.MaxProcessesAndOrThreads,
		EnablePerProcessAndThreadTimeLimit:   s.EnablePerProcessAndThreadTimeLimit,
		EnablePerProcessAndThreadMemoryLimit: s.EnablePerProcessAndThreadMemoryLimit,
		MaxFileSize:                          s.MaxFileSize,
		CompileOutput:                        s.CompileOutput,
		ExitCode:                             s.ExitCode,
		ExitSignal:                           s.ExitSignal,
		Message:                              s.Message,
		WallTime:                             s.WallTime,
		CompilerOptions:                      s.CompilerOptions,
		CommandLineArguments:                 s.CommandLineArguments,
		RedirectStderrToStdout:               s.RedirectStderrToStdout,
		CallbackUrl:                          s.CallbackUrl,
		AdditionalFiles:                      s.AdditionalFiles,
		EnableNetwork:                        s.EnableNetwork,
		StartedAt:                            s.StartedAt,
		QueuedAt:                             s.QueuedAt,
		UpdatedAt:                            s.UpdatedAt,
		QueueHost:                            s.QueueHost,
		ExecutionHost:                        s.ExecutionHost,
	}
}
