// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"-"`
}

type ProgrammingLanguage struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Question struct {
	ID               int32       `json:"id"`
	LanguageID       int32       `json:"language_id"`
	TemplateFunction pgtype.Text `json:"template_function"`
	Title            string      `json:"title"`
	Description      pgtype.Text `json:"description"`
	Score            int32       `json:"score"`
	Difficulty       int32       `json:"difficulty"`
}

type Room struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type RoomPlayer struct {
	RoomID   int32       `json:"room_id"`
	PlayerID int32       `json:"player_id"`
	Score    pgtype.Int4 `json:"score"`
	Place    pgtype.Int4 `json:"place"`
}

type TestCase struct {
	ID                 int32         `json:"id"`
	QuestionID         int32         `json:"question_id"`
	QuestionLanguageID int32         `json:"question_language_id"`
	Input              string        `json:"input"`
	ExpectedOutput     string        `json:"expected_output"`
	TimeConstraint     pgtype.Float8 `json:"time_constraint"`
	SpaceConstraint    pgtype.Int4   `json:"space_constraint"`
}
