// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID         int32
	Name       pgtype.Text
	CompileCmd pgtype.Text
	RunCmd     pgtype.Text
	SourceFile pgtype.Text
	IsArchived pgtype.Bool
}

type Player struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"-"`
}

type Question struct {
	ID               int32
	LanguageID       int32
	TemplateFunction pgtype.Text
	Title            string
	Description      pgtype.Text
	Score            int32
	Difficulty       int32
}

type Room struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type RoomPlayer struct {
	RoomID   int32       `json:"room_id"`
	PlayerID int32       `json:"player_id"`
	Score    pgtype.Int4 `json:"score"`
	Place    pgtype.Int4 `json:"place"`
	State    pgtype.Text `json:"state"`
}

type Submission struct {
	ID                                   int32
	SourceCode                           pgtype.Text
	LanguageID                           pgtype.Int4
	Stdin                                pgtype.Text
	ExpectedOutput                       pgtype.Text
	Stdout                               pgtype.Text
	StatusID                             pgtype.Int4
	CreatedAt                            pgtype.Timestamp
	FinishedAt                           pgtype.Timestamp
	Time                                 pgtype.Numeric
	Memory                               pgtype.Int4
	Stderr                               pgtype.Text
	Token                                pgtype.Text
	NumberOfRuns                         pgtype.Int4
	CpuTimeLimit                         pgtype.Numeric
	CpuExtraTime                         pgtype.Numeric
	WallTimeLimit                        pgtype.Numeric
	MemoryLimit                          pgtype.Int4
	StackLimit                           pgtype.Int4
	MaxProcessesAndOrThreads             pgtype.Int4
	EnablePerProcessAndThreadTimeLimit   pgtype.Bool
	EnablePerProcessAndThreadMemoryLimit pgtype.Bool
	MaxFileSize                          pgtype.Int4
	CompileOutput                        pgtype.Text
	ExitCode                             pgtype.Int4
	ExitSignal                           pgtype.Int4
	Message                              pgtype.Text
	WallTime                             pgtype.Numeric
	CompilerOptions                      pgtype.Text
	CommandLineArguments                 pgtype.Text
	RedirectStderrToStdout               pgtype.Bool
	CallbackUrl                          pgtype.Text
	AdditionalFiles                      []byte
	EnableNetwork                        pgtype.Bool
	StartedAt                            pgtype.Timestamp
	QueuedAt                             pgtype.Timestamp
	UpdatedAt                            pgtype.Timestamp
	QueueHost                            pgtype.Text
	ExecutionHost                        pgtype.Text
}

type TestCase struct {
	ID                 int32
	QuestionID         int32
	QuestionLanguageID int32
	Input              string
	ExpectedOutput     string
	TimeConstraint     pgtype.Float8
	SpaceConstraint    pgtype.Int4
}
